### ISSUE TITLE
Onboard wifi is not usable

### ISSUE THREAD

**Issue by sheepsong** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#2]
The efi is working perfectly, except the onboard wifi is not working. 
![image](https://user-images.githubusercontent.com/8043304/144742649-ba8a7910-2f33-4f83-bdad-6d47d5f2b346.png)
I was using a Fenvi TV919 before updating to Monterey.

**Comment by ankanpratik** [comment]
Hey thanks for the feedback. Since the past few months I've shifted from using Fenvi TV919 to using the onboard wi-fi. This gave me better stability than the bluetooth of Fenvi. If you would still like to use that, remove 3 files from the Kext folder: BlueToolFixup.kext, IntelBluetoothFirmware.kext and IntelBluetoothInjector.kext and from the config.plist file as well. Should work out of the box.

**Comment by sheepsong** [comment]
Thanks a lot! Now all is back to normal.
I would like to try removing the Fenvi T919 and using only the onboard wi-fi too. Bluetooth is really not very stable when my cell phone is near around.
