### ISSUE TITLE
Which SMBios?

### ISSUE THREAD

**Issue by jamesfawcett** [ankanpratik/Gigabyte-Z490-AORUS-Pro-AX-EFI-OpenCore#3]
Hi @ankanpratik 

Which Smbios are you using please? 20,2? 

I have been using my z490 as a Hackintosh for a year now, but I am struggling to get audio working in Monterey, would like to try your repo.

I also have Fenvi T919, I am interested to try the on board wifi :)

**Comment by ankanpratik** [comment]
I've been using iMacPro 1,1 since long before High Sierra, and it has frankly been working well for me. iMac 20,2 'should' work fine too I guess.

If you're planning to use Fenvi then I would suggest to remove it before you try the onboard one as it caused issues on my system. Without it, the onboard Bluetooth works flawlessly and has better reception.

**Comment by jamesfawcett** [comment]
@ankanpratik thank you! I will do the same and remove it first! 

This is the repo I have been mirroring since I began, but tweaking it for the Z490. I've changed graphic cards a few times and now I'm using an RX580. https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D

I am having trouble with sleep too since Monterey, I created my USB map correctly but for some reason, it doesn't hibernate anymore. I will try with your repo to compare :) When I run `pmset -g assertionslog|grep -i sleep` nothing is shown. Does yours sleep ok?

**Comment by jamesfawcett** [comment]
@ankanpratik thank you! I will do the same and remove it first! 

This is the repo I have been mirroring since I began, but tweaking it for the Z490. I've changed graphic cards a few times and now I'm using an RX580. 

I am having trouble with sleep too since Monterey, I created my USB map correctly but for some reason, it doesn't hibernate anymore. I will try with your repo to compare :) When I run `pmset -g assertionslog|grep -i sleep` nothing is shown. Does yours sleep ok?

**Comment by ankanpratik** [comment]
Unfortunately Sleep is still an issue. It was basically working before Monterey but now it's still wakes up for some reason. Mainly I think it's because I'm using the on-board wi-fi as opposed to Fenvi as before. Will get back on this some other day.

I too began using the Vision D Opencore before and made changes to the EFI for Pro AX, but since 0.7.4, this is a fresh OpenCore made from scratch so as to keep it light and 'updatable'. Will look into how the devs fixed the Sleep and the USB Map in another revision.

**Comment by jamesfawcett** [comment]
Thank you, if I can solve sleep I will report back :)

**Comment by jamesfawcett** [comment]
@ankanpratik I'm very impressed with the on-board wifi and bluetooth!

I can now pickup wifi networks I couldn't see before.

Bluetooth is super strong too!

I was hoping that you might have had an audio layout with headphones, I might just revert back to hda-gfx for now to get that working

```
<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
			<dict>
				<key>hda-gfx</key>
				<string>onboard-1</string>
				<key>layout-id</key>
				<integer>28</integer>
				<key>device-id</key>
				<data>cKEAAA==</data>
			</dict>|
			```

**Comment by ankanpratik** [comment]
Oh, that's correct. I haven't tried the wired output options yet, but this should work. I'll try this too on my end.

The only demerit is Airdrop doesn't support over in-built one. Might as well prefer good wi-fi and Bluetooth than AirDrop I guess. :)

**Comment by jamesfawcett** [comment]
Hi @ankanpratik 

Headphones and all audio are working correctly:

![image](https://user-images.githubusercontent.com/5245272/156849507-c046eedd-6bcc-4ad6-9603-8243111d9b68.png)

The correct device is :

`<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
			<dict>
				<key>hda-gfx</key>
				<string>onboard-1</string>
				<key>layout-id</key>
				<integer>28</integer>
				<key>device-id</key>
				<data>cKEAAA==</data>
			</dict>`

I am now working on the USB port mapping. For some reason generating and using SSDT-EC-USBX.aml and SSDT-UIAC.aml is not working so I'll try by kext.

_________________

Edit - whilst this works for headphones and correcting the audio ports, when PciRoot(0x0)/Pci(0x1F,0x3) is set to hda-gfx it seems to make the system crash roughly every 10 mins or so. I will try fix it :)

**Comment by ankanpratik** [comment]
Awesome! Thanks for the inputs @jamesfawcett, appreciate it! I've since fixed the Audio without using hda-gfx and it all seems to be working stable and fine on my end. Please check the Beta release and let me know!

Also happy to report the Sleep is somewhat functioning, but it's a hit or miss approach. Most of the time the on-board wifi is making the system turn on. Hopefully will fix it soon.

I've removed the USBPorts.kext and the two aml files mentioned by you. The ports are still working but they are not defined properly. Will fix those in the update as well.

**Comment by jamesfawcett** [comment]
This is great news! I will be back home tomorrow to test this out!

The bluetooth signal by the way.... extends my whole house! My bluetooth headphones work everywhere the signal is so good! 

I remember having to add `uia_exclude=HS14` to my boot-args at some point. I think that might have been on shmocklord's original repo to disable the onboard wifi. I might be mistaken though! I've kept it in my boot-args ever since.

**Comment by jamesfawcett** [comment]
Morning @ankanpratik 

I went through all the ALC layouts and layout 28 works perfectly for me. I've only put it in boot-args so far I haven't made it permanent yet:

<key>boot-args</key>
<string>agdpmod=pikera shikigva=80 keepsyms=1 alcid=28</string>

No crashing, digital output and headphones all working :) 

![image](https://user-images.githubusercontent.com/5245272/157200904-ee199464-2ca4-4f13-8d8f-5e7a47b672e0.png)

I've also attached my working USB outputs, I had to re-enable hs14 I can confirm that is the on board bluetooth. You are correct though, it does prevent sleep! :( I don't want to go back to the Fenvi though just yet!

![image](https://user-images.githubusercontent.com/5245272/157201160-b3ea6231-fc6c-4ea9-a45b-55cb524f1833.png)

**Comment by ankanpratik** [comment]
Awesome news @jamesfawcett! I've since tested with a different approach and happy to say this works perfectly. No need to add boot-args too. Also are you using something other than iMac1,1 configuration? shikigva isn't needed for me and all the DRM works on Safari as well as Chrome.
![Screenshot 2022-03-08 at 7 17 55 PM](https://user-images.githubusercontent.com/9656361/157250735-09b92f5c-9d39-4ef0-87f5-b2a2d44cdde3.png)

The USB Map looks good, but have to delete rest of the unnecessary extra values and limit it to 15-port only. @SchmockLord had done this correctly. (I think we could copy almost the same layout/configuration, apart from the hs14 part.)
![image](https://user-images.githubusercontent.com/9656361/157252848-d9712e1c-c403-485a-92b7-0e6bc9577644.png)

**Comment by jamesfawcett** [comment]
I think, but I might be wrong, that the usb ports I've set to **internal** are not counted as part of the 15 port limit? I think so anyway, but I may be wrong! When I disable hs14, sleep works for me, but I lose bluetooth if it's not set to USB2/USB3. 

I am using Smbios 20,2.

What's the first screenshot from please? That looks like a useful tool! 

Thanks for the tips on the boot-args I will remove those! :) 

Tomorrow I am having broadband installed so I will test out the ethernet.

**Comment by ankanpratik** [comment]
That's OCAT, quite helpful!
https://github.com/ic005k/OCAuxiliaryTools

**Comment by jamesfawcett** [comment]
Thanks for all your help! I actually put the Fenvi back in as I was getting frequent drop outs where I would need to restart the network device. The onboard bluetooth was awesome though! But, I couldn't get sleep working. Back to the Fenvi now for me, but I'm going to keep watching for future progress :)
